{% set name = "m17-cxx-demod" %}
# Note: we mistakenly created this feedstock with the url pointing at n1ai's
# fork with a version that is not from the upstream mobilinkd source. Once the
# next official version is released, we need to sync the version.
{% set version = "2.3.3" %}
{% set tag_version = ".".join(version.split(".", 2)[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mobilinkd/m17-cxx-demod/archive/refs/tags/v{{ tag_version }}.tar.gz
  sha256: 5dac28a7aa0c252e06b1ef1723acf0ddb6630a2a8ede07f15809cd2faef0b367
  patches:
    - 0001-avoid-experimental-array-and-MAX_INPUT.patch
    - 0002-avoid-experimental-array-in-apps-dir.patch
    - 0003-redefine-__builtin_popcount-for-MSVC.patch
    - 0004-Specify-compilation-options-definitions-for-MSVC.patch
    - 0005-Switch-struct-packing-to-command-that-is-compatible-.patch
    - 0006-Use-std-popcount-instead-of-__builtin_popcount-for-p.patch
    - 0007-Use-unlikely-attribute-instead-of-__builtin_expect-f.patch
    - 0008-Use-.data-instead-of-.begin-on-std-array-when-a-poin.patch
    - 0009-Switch-to-use-find_package-for-codec2-link-with-code.patch
    - 0010-Link-only-with-imported-CMake-targets.patch

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.9
    - ninja
    - pkg-config
  host:
    - libboost-devel
    - gtest
    - gmock
    - libcodec2
  run:

test:
  commands:
    # verify that commands run (will print usage statement)
    - m17-mod --help
    - m17-demod --help
    # verify that (some) headers get installed
    - test -f $PREFIX/include/m17cxx/M17Modulator.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\m17cxx\\M17Modulator.h exit 1  # [win]

about:
  home: https://github.com/mobilinkd/m17-cxx-demod
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: M17 Modulator & Demodulator in C++ (GPL)
  description: |
    m17-cxx-demod from mobilinkd has programs that modulate or demodulate data according to the M17 specification https://m17-project.github.io/M17_spec
  doc_url: https://github.com/mobilinkd/m17-cxx-demod/blob/master/README.md
  dev_url: https://github.com/mobilinkd/m17-cxx-demod

extra:
  recipe-maintainers:
    - n1ai
    - ryanvolz
